### ISSUE TITLE
What about carthage support?

### ISSUE THREAD

**Issue by Danappelxx** [neonichu/cato#10]
Cocoapods is great, but a lot of libraries don't have a podspec/don't work through it. It would be nice to either pick carthage globally, fallback to carthage if rome fails, or somethings like this:

``` swift
import Alamofire // Carthage
```

Just an idea :P

**Comment by neonichu** [comment]
Thanks for the suggestion, but this is a bit out of scope for this, as it would require a bunch more code to integrate with Carthage. Maybe https://github.com/owensd/apous is the better choice for you, though.
