### ISSUE TITLE
Brew can't find dependencies

### ISSUE THREAD

**Issue by alexito4** [neonichu/cato#12]
Hi!
Sorry to disturb you but I was trying to install `cato` in order to make scriptiing easier and I found this error when running `brew install cato`

```
==> Installing cato from neonichu/formulae
cato: Unsatisfied dependency: cocoapods
Homebrew does not provide Ruby dependencies; install with:
  gem install cocoapods
cato: Unsatisfied dependency: cocoapods-rome
Homebrew does not provide Ruby dependencies; install with:
  gem install cocoapods-rome
Error: Unsatisfied requirements failed this build.
```

I think the issue is that brew tries to look for the gems in a different directory that where they are. I use RVM so for example cocoapods is in `/Users/alex/.rvm/gems/ruby-2.2.1/bin/pod`. Also the ruby version that is being used via the PATH is `/Users/alex/.rvm/rubies/ruby-2.2.1/bin/ruby` but I guess brew uses the system one?

I know that this is not related directly to cato but any help would be really appreciated ;)

**Comment by neonichu** [comment]
IDK anything about using RVM, but Homebrew appears to use the ruby it can find in the environment, see https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/requirements/language_module_requirement.rb#L33

If you cannot figure out how to fit RVM and Homebrew together, another option would be to fork my formulae and remove those dependencies from your copy of the formula, as you have manually verified that they are satisfied.

¯\_(ツ)_/¯

**Comment by alexito4** [comment]
Thanks for the tip. 
Will take a look ;) Cheers.

**Comment by neonichu** [comment]
If nothing helps, there's always:

![](https://media.giphy.com/media/M11UVCRrc0LUk/giphy.gif)
