### ISSUE TITLE
Can't use

### ISSUE THREAD

**Issue by nghiaphunguyen** [neonichu/cato#14]
Hi neonichu
I installed all stuffs and it worked in the first time. After that, it always fail. Error like that:
no such module 'Chores'
import Chores
       ^

Have you any idea for that? Thanks

**Comment by neonichu** [comment]
Switching Swift or Xcode versions could be a problem, since the compilation only happens once and there's no cache invalidation. So my recommendation would be to delete cached files in `$HOME/.📦` and let downloads/compilation happen from scratch.

**Comment by neonichu** [comment]
This is related to #4 — there should be an easier way to reset the cached data.

**Comment by nghiaphunguyen** [comment]
I found the reason, i ran with command "swift file.swift" instead of "./file.swift" :'(
