### ISSUE TITLE
Example Doesn't Work

### ISSUE THREAD

**Issue by madhavajay** [neonichu/cato#16]
Example file as per README:

```
#!/usr/bin/env cato

import Chores

let result = >["xcodebuild", "-version"]
print(result.stdout)
```

After running it:

```
Analyzing dependencies
Downloading dependencies
Installing Chores (0.0.3)
Generating Pods project
Skipping User Project Integration
Building frameworks
[!] /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -project Pods.xcodeproj -scheme Pods-cato -configuration Release -sdk macosx

Build settings from command line:
    SDKROOT = macosx10.12

xcodebuild: error: 'Pods.xcodeproj' does not exist.
```

Any idea why?

**Comment by neonichu** [comment]
Sorry, as said in the README, this project is unmaintained now.

**Comment by madhavajay** [comment]
Yeah sorry I see that now. Pity it seemed like a great idea, do you know if theres anything out there which replaces this? Id really love a nice, virtualenv / pip style experience for swift. I see theres swiftenv already, now we just need something to handle dependencies for shebang style scripting.
